### ISSUE TITLE
setup.py skips necessary directories

### ISSUE THREAD

**Issue by ragouel** [riotkit-org/riotkit-do#21]
python version 3.8.3

`rkd/misc`
`rkd/internal` 

are not copied over during the installation resulting in a buggy mess (banner.txt).

<pre><code>python setup.py install</code></pre>

**Comment by blackandred** [comment]
Thanks for the report, I will fix it within RKD 1.1 scheduled to be released on Sunday.
It would be nice to somehow cover this case with unit tests, this is not covered because unit tests are using local module without setuptools :confused:

**Comment by blackandred** [comment]
I installed via `setup.py install` in a local fresh VM (using vagrant) with Python 3.7.3

```
vagrant@buster:~/riotkit-do$ ls -la /usr/local/lib/python3.7/dist-packages/rkd/misc/
total 16
drwxr-sr-x 3 root staff 4096 Jun 19 06:43 .
drwxr-sr-x 6 root staff 4096 Jun 19 06:43 ..
-rw-r--r-- 1 root staff 2378 Jun 19 06:42 banner.txt
drwxr-sr-x 3 root staff 4096 Jun 19 06:43 initial-structure
vagrant@buster:~/riotkit-do$ ls -la /usr/local/lib/python3.7/dist-packages/rkd/internal/
total 16
drwxr-sr-x 3 root staff 4096 Jun 19 06:43 .
drwxr-sr-x 6 root staff 4096 Jun 19 06:43 ..
-rw-r--r-- 1 root staff  741 Jun 19 06:42 makefile.py
drwxr-sr-x 2 root staff 4096 Jun 19 06:43 __pycache__
```

The directories are installed.

Could you tell me how to reproduce it?
Can you paste any logs? :wink:

**Comment by blackandred** [comment]
Second test: I destroyed the VM, then created again, installed PIP for Python3, wheel, setuptools, then made pip install rkd. The banner shows on `rkd` and the task list shows on `rkd :tasks`

**Comment by ragouel** [comment]
Tried it with [1.0.0](https://github.com/riotkit-org/riotkit-do/archive/v1.0.0.tar.gz) for Python 3.8.3 inside a [build script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=riotkit-do)

**Comment by ragouel** [comment]
It seems the issue is not present in the git version. Closing.

**Comment by blackandred** [comment]
Oh nice, I'm using actually Arch Linux. Ok, then on Sunday in 1.1 release it should work. I suggest then that you can use 1.1 in PKGBUILD when it will be released.

**Comment by ragouel** [comment]
Yes, I'll update.

**Comment by blackandred** [comment]
RKD 1.1 was just released.

https://github.com/riotkit-org/riotkit-do/releases/tag/v1.1

**Comment by ragouel** [comment]
Still, same issue. I'm attaching latest PKGBUILD so you can do some testing.

<pre><code>Traceback (most recent call last):
  File "/usr/bin/rkd", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/rkd/__init__.py", line 78, in main
    app.main(argv=sys.argv)
  File "/usr/lib/python3.8/site-packages/rkd/__init__.py", line 38, in main
    self.print_banner_and_exit()
  File "/usr/lib/python3.8/site-packages/rkd/__init__.py", line 66, in print_banner_and_exit
    with open(os.path.dirname(os.path.realpath(__file__)) + '/misc/banner.txt', 'rb') as banner_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.8/site-packages/rkd/misc/banner.txt'</code></pre>

**PKGBUILD**
<pre><code>pkgname=riotkit-do
pkgver=1.1
pkgrel=1
pkgdesc='Task executor - balance between Makefile and Gradle. Written in Python. Powerful tool for every DevOps. Automates production tasks as well as local development tasks'
arch=('any')
url='https://github.com/riotkit-org/riotkit-do'
license=('Apache')
depends=('python-yaml'
         'python-pbr'
         'python-jinja'
         'python-dotenv'
         'python-tabulate')
makedepends=('python-setuptools')
source=("${pkgname}-${pkgver}.tar.gz::https://github.com/riotkit-org/riotkit-do/archive/v${pkgver}.tar.gz")
sha256sums=('67f9061f168fa4a8d878633e11f9d44b590fce887bc0a6922e88894ac6a73fb2')

prepare() {
  cd "${pkgname}-${pkgver}"
  sed -i "s|==|>=|g" requirements.txt
}

build() {
  cd "${pkgname}-${pkgver}"
  python setup.py build
}

package() {
  cd "${pkgname}-${pkgver}"
  python setup.py install --root="$pkgdir" --optimize=1 --skip-build
  install -d "${pkgdir}/usr/share/doc/${pkgname}"
  cp -R docs/* "${pkgdir}/usr/share/doc/${pkgname}"
}</code></pre>

**Comment by blackandred** [comment]
Ok, I will try to build your PKGBUILD and let you know :wink:

**Comment by blackandred** [comment]
1. `python-dotenv` does not exist (had to remove it temporarily)
2. 
```
raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name rkd was given, but was not able to be found.
error in setup command: Error parsing /tmp/rkd-pkg/src/riotkit-do-1.1/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name rkd was given, but was not able to be found.
```

I got this - it means that you need to clone a version from git to build eg. `git clone https://github.com/riotkit-org/riotkit-do.git && git checkout v1.1` because project is using PBR (commonly used in Python projects) that is relying on GIT to know it's own version :wink: 

Other possibility would be to install via pip to local directory and grab files.

**Comment by ragouel** [comment]
[python-dotenv](https://www.archlinux.org/packages/community/any/python-dotenv/) exists.
I will just copy over the required folders, then. Since, it's too much of a hassle to resolve it through setup.py.

**Comment by ragouel** [comment]
Works, from the looks of it. [riotkit-do](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=riotkit-do)

**Comment by ragouel** [comment]
Let me know if you want me to transfer ownership to you.

**Comment by blackandred** [comment]
Thank you very much. I don't need to, too much concentration of 'ownership' is not good for me :wink:

**Comment by blackandred** [comment]
Regarding python-dotenv, that's weird:

```
$ yaourt -Ss python-dotenv
$
```

:joy:

**Comment by ragouel** [comment]
Manjaro have their own repositories.
